# Copyright 2023 Salesforce, Inc. All rights reserved.
[template]
cargo_generate_version = ">=0.10.0"
ignore = [
    "kilonova.yaml",
    "Dockerfile",
    "Jenkinsfile",
    "Readme.md",
    ".git",
    ".gitignore",
    ".github",
    ".idea",
    ".devcontainer/",
    ".vscode/launch.json",
    ".vscode/tasks.json",
    "docs/",
    "scripts/",
    ".dockerignore",
    ".gitpod.Dockerfile",
    ".gitpod.yml",
]

[placeholders.asset-version]
type = "string"
prompt = "Please provide an initial version for the policy to create"

[placeholders.group-id]
type = "string"
prompt = "Please provide the group-id of the policy assets"

[placeholders.asset-id]
type = "string"
prompt = "Please provide an asset-id for the policy"

[placeholders.anypoint-registry-url]
type = "string"
prompt = "Please provide the URL of the Anypoint registry"

[hooks]
post = ["post-script.rhai"]
