# Copyright 2023 Salesforce, Inc. All rights reserved.
[template]

[placeholders.asset-version]
type = "string"
prompt = "Please provide an initial version for the policy to create"

cargo_generate_version = ">=0.10.0"
ignore = [
    "kilonova.yaml",
    "Dockerfile",
    "Jenkinsfile",
    "Readme.md",
    ".git",
    ".github",
    ".idea",
    ".devcontainer/",
    ".vscode/launch.json",
    ".vscode/tasks.json",
    "docs/",
    "scripts/",
    ".dockerignore",
    ".gitpod.Dockerfile",
    ".gitpod.yml",
]

[hooks]
post = ["post-script.rhai"]
