# Copyright 2023 Salesforce, Inc. All rights reserved.
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Extension
metadata:
  name: simple-oauth2-validation
spec:
  extends:
  - name: envoy-filter
  - name: proxy-wasm-filter
  properties:
    rootId:
      type: string
      default: main
    tokenExtractor:
      type: string
      format: dataweave
      default: "#[dw::core::Strings::substringAfter(attributes.headers['Authorization'], 'Bearer ')]"
    upstream:
      type: string
    host:
      type: string
    path:
      type: string
    authorization:
      type: string
    implementation:
      type: string
      default: base64://<ENCODED>
  required:
    - tokenExtractor
    - upstream
    - host
    - path
    - authorization
